### ISSUE TITLE
flowConfig is undefined

### ISSUE THREAD

**Issue by bmsekni** [flowjs/ngx-flow#10]
Hi, 
I'm trying to setup my flow using a constant inside my component.
![image](https://user-images.githubusercontent.com/45198954/49070076-1f73d300-f22b-11e8-915e-f39f2366def6.png)
and
![image](https://user-images.githubusercontent.com/45198954/49070107-30244900-f22b-11e8-944d-6c7354f209e1.png)

i can see that my flow.flowConfig is undefined, is that normal ?

Link: https://stackblitz.com/edit/ngx-flow-example-iqognh

**Comment by MartinNuc** [comment]
The reason is because `flowConfig` is just a setter for input. It has no getter therefore you cannot print out its value.

If you really need to see what options are used for given directive you can use `flow.flowJs.opts`. This is the options property managed by flowjs itself.

**Comment by Godstrump** [comment]
I have the same issue. Here my 
`[flowConfig]="{ target: 'http://localhost:3333/document' }`
does not reach the document controller.
`
