### ISSUE TITLE
Issue when importing the library

### ISSUE THREAD

**Issue by azael-leal** [flowjs/ngx-flow#106]
Hello, I'm having an issue importing the library (image below). I'm using Angular: v11.2.3 and tried different ways to import it but all of them throw the same errors. Can someone help me with this issue?

![Console Errors](https://github.com/flowjs/ngx-flow/assets/55031967/1b393be2-84d9-415b-aca5-886f14762ac9)

**Comment by CosmoFruit** [comment]
@azael-leal  Hi, which version ngx-flow do you use?
it seems you try use Ivy compatible build with old version Angular.
You need use more low version of ngx-flow  (which compatible with 11 version), or update you Angular to 16 version
