### ISSUE TITLE
Directory drag and drop does not work

### ISSUE THREAD

**Issue by ToshihiroNozaki** [flowjs/ngx-flow#11]
Hi.
Directory D&D does not work in [demo site](https://stackblitz.com/edit/ngx-flow-example-iqognh)
Is Directory D&D supported by ngx-flow?

**Comment by MartinNuc** [comment]
Directory upload is not in demo site but it's covered in [README](https://github.com/flowjs/ngx-flow#i-want-to-upload-whole-directory).

If it doesn't work we can reopen this issue.
