### ISSUE TITLE
Latest version not supported with Angular 15

### ISSUE THREAD

**Issue by niranjan1988** [flowjs/ngx-flow#111]
I upgraded ngx-flow from 0.6.0 to 0.7.0 / 0.7.2 on my app which is using angular 15. The build is giving below error

![flow](https://github.com/flowjs/ngx-flow/assets/10009142/a54603c7-f20f-4bad-a1cf-da330918f2f8)

Is it issue due to the angular version i am using?

**Comment by niranjan1988** [comment]
@Hilario-Rodriguez could you comment as you upgraded the library to to support angular 16 app from angular 14.

**Comment by Quentigus** [comment]
@niranjan1988, 0.7.0 version is for Angular 16,you can't use it with Angular 15.

There is no release for Angular 15, have you any error with Angular 15/0.6.0 (install, build, serve,...)?

**Comment by niranjan1988** [comment]
@Quentigus i am facing error during build and start. Error snapshot can be seen in the above description

**Comment by Quentigus** [comment]
This error is due to major update of Typescript.

Library compiled with Angular 16 doesn't have backwards compatibility.
