### ISSUE TITLE
NgxFlowModule not found in @flowjs/ngx-flow since 0.8.0

### ISSUE THREAD

**Issue by sebastiencl** [flowjs/ngx-flow#114]
Since the last update, `FlowInjectionToken `and `NgxFlowModule `no longer seem to be exported.
Did I miss something?

**Comment by Quentigus** [comment]
@evilaliv3, this version seems to be published without any compilation.

❌ 0.8.0 : https://www.npmjs.com/package/@flowjs/ngx-flow?activeTab=code
vs
✅ 0.7.2 : https://www.npmjs.com/package/@flowjs/ngx-flow/v/0.7.2?activeTab=code


https://github.com/flowjs/ngx-flow/issues/97#issuecomment-1932093755

**Comment by sebastiencl** [comment]
It's work well with 0.8.1

**Comment by evilaliv3** [comment]
Thank you for the feedback @sebastiencl
