### ISSUE TITLE
add flowAttributes property to flowDrop

### ISSUE THREAD

**Issue by Hasan-git** [flowjs/ngx-flow#13]
is there any way to specify file attributes in case of flowDrop ? 

where adding flowAttributes to flowDrop  directive its throwing an error : 
" **Can't bind to 'flowAttributes' since it isn't a known property ..** "

**Comment by MartinNuc** [comment]
flow's [assignDrop](https://github.com/flowjs/flow.js#methods) doesn't accept attributes therefore attributes are consumed only by `flowButton` directive.

If this will be implemented by original flowjs I will add it also here.
