### ISSUE TITLE
Cannot read property 'events$' of undefined

### ISSUE THREAD

**Issue by greatsayan** [flowjs/ngx-flow#14]
Hi,

Thanks for the plugin!!
I have an issue when I'm trying to subscribe to events$ from FlowDirective but I have this error:
**Cannot read property 'events$' of undefined.**
I can easily reproduce it in the demo(https://stackblitz.com/edit/ngx-flow-example). Just comment all the html part related to the Advanced example (from line 15 to the end) then the error should appear in the console.
How can I subscribe to those events? I'm not using the drag-drop part. I just want to select a file then upload it!
Thanks in advance.

**Comment by MartinNuc** [comment]
Hey,
you need a reference for `flow`

```
  @ViewChild('thisComesFromTemplate')
  flow: FlowDirective;
```

Notice `thisComesFromTemplate` string. Thats a reference for a template variable. For example: 
```
<ng-container #thisComesFromTemplate="flow" [flowConfig]="{target: '/'}"></ng-container>
```

Also remember to subscribe in `ngAfterViewInit` or after. I forked example: https://stackblitz.com/edit/ngx-flow-example-atxgjh

Hope it helps :-)

**Comment by greatsayan** [comment]
Ho yes my bad, I forgot to implement the reference with ViewChild...
Thanks for your quick response!
