### ISSUE TITLE
Update to Angular 7

### ISSUE THREAD

**Issue by bmsekni** [flowjs/ngx-flow#16]
Hi,

Any plans to update to NG 7 ?

**Comment by MartinNuc** [comment]
Doesnt work with Angular7?

**Comment by MartinNuc** [comment]
I see dependency is set to Angular 6. It should work just fine with 7. I will update dependency requirements.

**Comment by MartinNuc** [comment]
peerDependencies bumped to support Angular7. Try 0.3.5 please.
