### ISSUE TITLE
how to add custom query

### ISSUE THREAD

**Issue by Hasan-git** [flowjs/ngx-flow#17]
I need a way to add custom query parameter for each file ?
I tried :
`file.flowObj.opts.query["id"] = '....'`
unfortunately, it updates all files query with the same query value

**Comment by begust** [comment]
I'm trying to use this solution.  I have a similar problem. but when this event fires 'this' is null.  I do not have access back to my local variables.  any suggestions?

**Comment by MartinNuc** [comment]
@begust use arrow function:

```typescript
this.mediaFlow.flowJs.opts.query = (file, chunk) => {       

        // @ some code...

        return { custom: 'whatever' }
    }
```

**Comment by begust** [comment]
Thank you.  works perfect.
