### ISSUE TITLE
Unable to get the uploaded response

### ISSUE THREAD

**Issue by suriyagp** [flowjs/ngx-flow#18]
Once after the upload i need to get the response of the upload request to proceed further. that is available in the normal ng-flow but not in ngx-flow

**Comment by MartinNuc** [comment]
I will take a look into it.

**Comment by MartinNuc** [comment]
@suriyagp can you please point me how do you do it with ng-flow or preferably with flow.js?

**Comment by tahir-jamil** [comment]
any updates

**Comment by MartinNuc** [comment]
Point me please to docs how to do it using ng-flow or flow.js.

**Comment by hpwd** [comment]
i'm watching the fileError event and read the request message like this:


`    ngAfterViewInit() {

        this.autoUploadSubscription = this.flow.events$.subscribe(event => {

            if (event.type === 'filesSubmitted') {
                this.flow.upload();
            }

            if (event.type === 'fileError') {
                let response = JSON.parse( event.event[2].xhr.response );
                console.log( response.message );
                this.flow.cancel();
            }

        });
    }`

**Comment by MartinNuc** [comment]
Closing this issue. Solved by @hpwd
