### ISSUE TITLE
Unsupported events: fileAdded, complete

### ISSUE THREAD

**Issue by AlesWojnar** [flowjs/ngx-flow#19]
Ngx-flow does not support all Flow.js events (fileAdded, complete).

**Comment by MartinNuc** [comment]
You're right. Looks like it's missing [here](https://github.com/flowjs/ngx-flow/blob/master/projects/ngx-flow/src/lib/flow.directive.ts#L60)

**Comment by hpwd** [comment]
Also need that :(

**Comment by MartinNuc** [comment]
Fixed in [0.4.2](https://github.com/flowjs/ngx-flow/releases/tag/0.4.2)
