### ISSUE TITLE
Handle FlowDirective in ts file

### ISSUE THREAD

**Issue by Pades9** [flowjs/ngx-flow#20]
Hello,

for my case I would like to use ngx-flow only for upload so I don't want to init flow in ng-container. Is it possible to handle everything like adding files and events only in app.component.ts without html file? I tried to `flow: FlowDirective = new FlowDirective();` But there are two required parameters. Also I tried init Flow and this is working but how can I implement events? Thanks for response.

```
import Flow from '@flowjs/flow.js';
...
flow: Flow = new Flow();
```

**Comment by MartinNuc** [comment]
Hello, ngx-shell is a set of directives to be used in the template. If you want to use is only programatically in TS file you should use [flow.js](https://github.com/flowjs/flow.js) without `ngx-flow`.
