### ISSUE TITLE
How to use assignBrowse

### ISSUE THREAD

**Issue by osmanraifgunes** [flowjs/ngx-flow#21]
In flow.js there are two methods to change view elements :

```
flow.assignBrowse(document.getElementById('browseButton'));
flow.assignDrop(document.getElementById('dropTarget'));
```

[Documentation ](https://github.com/flowjs/flow.js/blob/master/README.md#how-can-i-use-it)

Is there any implementation in ngx version.

**Comment by MartinNuc** [comment]
There are two directives - one for drop and one for click. Checkout demo in docs https://github.com/flowjs/ngx-flow/blob/master/README.md

**Comment by MartinNuc** [comment]
@osmanraifgunes did it help? Can I close the issue?

**Comment by osmanraifgunes** [comment]
Yes. Thank you.
