### ISSUE TITLE
Could not find a declaration file for module '@flowjs/flow.js'

### ISSUE THREAD

**Issue by prachivachhani** [flowjs/ngx-flow#27]
I have 
    "@flowjs/flow.js": "^2.14.0",
    "@flowjs/ngx-flow": "^0.4.3",
and 
    "@angular/common": "^5.2.6",
    "@angular/compiler": "^5.2.6",
    "@angular/core": "^5.2.6",

and I have the following error: 
Could not find a declaration file for module '@flowjs/flow.js'. 'NgApp/node_modules/@flowjs/flow.js/src/flow.js' implicitly has an 'any'
 type.
  Try `npm install @types/flowjs__flow.js` if it exists or add a new declaration (.d.ts) file containing `declare module '@flowjs/flow.js';`

Can anyone help me with this issue? 
Thank you.

**Comment by MartinNuc** [comment]
Not sure about type definitions for flowjs 2.14. In DefinitelyTyped there is only [2.13](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/efa34318e5397e3d99291e60c963ea5b70690842/types/flowjs/index.d.ts). We might need an update.

Can you please try with flowjs 2.13?

Also I am not sure about Angular 5. I think you need 8+.

**Comment by prachivachhani** [comment]
No, I tried using 2.13 as well but that didn't work. For now, it seems if I remove this line :     "noImplicitAny": true,  from tsconfig file...  it's working fine.

**Comment by touchsky2018** [comment]
@prachivachhani 

I have same problem in angular13, and no "noImplicitAny": true, but still not work for me.
any other way to resolve it
