### ISSUE TITLE
Improvement - update to angular 9 

### ISSUE THREAD

**Issue by wandri** [flowjs/ngx-flow#29]
Hello, 
With angular 9 comes Ivy by default. 

**ngx-flow works already well with angular 9.1.0** but I have noticed that there is some slight improvements with the build of the package with angular 9.

Is there a plan to migrate to the last version ? 9.1 ?

What I have tried : 

- `ng update` does the job.

- some changes can be done in the new created file `projects/ngx-flow/tsconfig.lib.prod.json` from the migration to accept Ivy:

```
{
  "extends": "./tsconfig.lib.json",
  "angularCompilerOptions": {
    "enableIvy": true
  }
}
```

- And `import 'core-js/es7/reflect';` need to be removed from `projects/ngx-flow/src/test.ts` because it isn't necessary anymore

Thanks !

**Comment by MartinNuc** [comment]
@wandri I haven't looked into Angular 9 yet 🙈 but I am open to PR's so if you manage to make a PR I will test it and we can make use of your tips
