### ISSUE TITLE
Publish package as @flowjs scoped package

### ISSUE THREAD

**Issue by MartinNuc** [flowjs/ngx-flow#3]
Currently I publish this package manually as [ngx-flow](https://www.npmjs.com/package/ngx-flow). We should move this under @flowjs npm account so its installed the same way as `@flowjs/flow.js`.

**Comment by AidasK** [comment]
@flowjs/developers who has access to npm @flowjs?

**Comment by AidasK** [comment]
@evilaliv3 ?

**Comment by evilaliv3** [comment]
Yep ywp

I just landed from a flight, will publish it as soon that I reach my place.

Will also see if I can share privileges of the account to more members of
the team

**Comment by evilaliv3** [comment]
Ok going to release it as 0.2.0 (that is the version already published here: https://www.npmjs.com/package/ngx-flow)

**Comment by MartinNuc** [comment]
Let me release 0.3.0 on github this evening and let's release that one on npm, ok?

**Comment by evilaliv3** [comment]
Ok! i'm ready for it.

If useful @AidasK grant me access for commit here so that i can contribute.

@MartinNuc the following changes will be necessary to ```package.json```:
```
commit 64cb158e1be0a22ae3e8a849c6d618ec60a777d1
Author: Giovanni Pellerano <giovanni.pellerano@evilaliv3.org>
Date:   Fri Sep 14 13:46:16 2018 +0200

    release 0.1.4

diff --git a/package.json b/package.json
index 1652e26..000367b 100644
--- a/package.json
+++ b/package.json
@@ -1,6 +1,6 @@
 {
-  "name": "ngx-flow-demo",
-  "version": "0.0.0",
+  "name": "@flowjs/ngx-flow",
+  "version": "0.1.4",
   "scripts": {
     "ng": "ng",
     "start": "ng serve",
@@ -11,7 +11,6 @@
     "lint": "ng lint",
     "e2e": "ng e2e"
   },
-  "private": true,
   "husky": {
     "hooks": {
       "pre-commit": "pretty-quick --staged"
```

**Comment by AidasK** [comment]
@evilaliv3 granted full access in all repos

**Comment by MartinNuc** [comment]
@evilaliv3 When publishing Angular2+ lib the root project should not be published but just the built directory. Let me explain in depth.

The root project is a wrapping project where you can play with your library. However the source of the library is located in [projects/ngx-flow](https://github.com/flowjs/ngx-flow/tree/master/projects/ngx-flow) folder.

When building library using `npm run build` it will prepare different package formats, TS exports etc. and place it in `dist/ngx-flow` folder. This is the folder which is supposed to be published.

Means you should first go into `dist/ngx-flow` and there run `npm publish`.

Also consider this is my first Angular2 lib so I might be mistaken in some parts.

The 0.3.0 is prepared: https://github.com/flowjs/ngx-flow/releases/tag/0.3.0

**Comment by MartinNuc** [comment]
As mentioned in https://github.com/flowjs/ngx-flow/issues/4#issuecomment-421540876 the package name in `projects/ngx-flow/package.json` should be `@flowjs/ngx-flowjs`. I will make that change.

I looked at [AngularJS version](https://github.com/flowjs/ng-flow/blob/master/package.json#L2) its called `@flowjs/ng-flow`. Is there a reason to add `js` suffix? I would prefer to differentiate them only by `ng` vs `ngx`. What do you think?

`@flowjs/ngx-flowjs` vs `@flowjs/ngx-flow`

**Comment by evilaliv3** [comment]
Correct to call it just @flowjs/ngx-flow @MartinNuc

**Comment by MartinNuc** [comment]
@evilaliv3 ok, I modified lib's `package.json` and tagged [0.3.2](https://github.com/flowjs/ngx-flow/releases/tag/0.3.2). Can you please try to publish it on npm?

**Comment by evilaliv3** [comment]
There it is!

**Comment by evilaliv3** [comment]
https://www.npmjs.com/~flowjs

For clearness with respect to users probably we should unpublish:
- https://www.npmjs.com/package/ngx-flow
- https://www.npmjs.com/package/ngx-flow-demo

To do that @MartinNuc you should execute with your user:
```npm unpublish ngx-flow --force```
```npm unpublish ngx-flow-demo --force```

**Comment by MartinNuc** [comment]
Thats a good point!

Unfortunately the process got more complicated :( https://blog.npmjs.org/post/141905368000/changes-to-npms-unpublish-policy

Therefore I deprecated the package and will contact npm support to remove it.

**Comment by MartinNuc** [comment]
@evilaliv3 There is a problem with published files. Before publishing you should run `npm run build` then go to `dist/ngx-flow` and from this directory run `npm publish`.

When I try to use `ngx-flow` in a project as dependency this is how it looks now:

![screen shot 2018-09-16 at 11 23 30](https://user-images.githubusercontent.com/681176/45594919-439d7300-b9a3-11e8-82f4-ee97244dd250.png)

However this is what files/folders should be published to npm:

![screen shot 2018-09-16 at 11 24 38](https://user-images.githubusercontent.com/681176/45594931-67f94f80-b9a3-11e8-96fb-b73ca15a8a51.png)

Feel free to bump the version to 0.3.3 if necessary.

**Comment by evilaliv3** [comment]
Ah! thanks for spotting this.

Yes from what i see on npm we are forced to make a dump of the versions.
I've removed the 0.3.2 but it do not accept it again.

Anyway before doing that i think we should first fix the build script:

It fails with:
```
user@development:~/Development/ngx-flow$ npm run build

> ngx-flow-demo@0.0.0 build /home/user/Development/ngx-flow
> ng build ngx-flow --prod && cp {README.md,LICENSE} ./dist/ngx-flow/

Building Angular Package
Building entry point '@flowjs/ngx-flow'
Rendering Stylesheets
Rendering Templates
Compiling TypeScript sources through ngc
Bundling to FESM2015
Bundling to FESM5
Bundling to UMD
Minifying UMD bundle
Copying declaration files
Writing package metadata
Removing scripts section in package.json as it's considered a potential security vulnerability.
Built @flowjs/ngx-flow
Built Angular Package!
- from: /home/user/Development/ngx-flow/projects/ngx-flow
- to:   /home/user/Development/ngx-flow/dist/ngx-flow
cp: cannot stat '{README.md,LICENSE}': No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ngx-flow-demo@0.0.0 build: `ng build ngx-flow --prod && cp {README.md,LICENSE} ./dist/ngx-flow/`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ngx-flow-demo@0.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-09-17T06_16_05_897Z-debug.log
```

would you like to check an let me know when i can publish it again?

**Comment by MartinNuc** [comment]
We need a chat to solve this. Apparently cp doesn't work the same way as on my system :-( do you have a chat place? Like gitter or something? Or we can contact each other on Twitter. My handle is: martin_nuc

**Comment by AidasK** [comment]
Maybe there is an option to add @MartinNuc and me to npm organisation?

**Comment by evilaliv3** [comment]
sure there is, would you please pass me both your nicknames?

This days i'm pretty busy and this way it result more easy for you to proceed directly. thank you!

**Comment by MartinNuc** [comment]
[martin.nuc](https://www.npmjs.com/~martin.nuc)

**Comment by MartinNuc** [comment]
@evilaliv3 the original `ngx-flow` was unpublished from npm. Currently there is no way to install this library. And we have a first issue about that: https://github.com/flowjs/ngx-flow/issues/6 :-(

**Comment by evilaliv3** [comment]
I'm sorry for the delay @MartinNuc 

I just converted my user account to an organization and added you and @AidasK to it: https://www.npmjs.com/org/flowjs

You find inside an other user that i had to create to do this conversion: i now asked npm people to delete my duplicated account (marirossievil) because it seems they do not let users delete their own accounts :)

**Comment by MartinNuc** [comment]
Thanks. I was able to publish 0.3.3 and verify its working in [demo](https://stackblitz.com/edit/ngx-flow-example).
