### ISSUE TITLE
 flow-drag-enter for Angular

### ISSUE THREAD

**Issue by MaximRobota** [flowjs/ngx-flow#33]
I didn't find opportunity to drug-drop active. I would add class `.active` when I'm dropping file in the area.

Do you have for Angular solution like in AngularJs?
Ex:
Use flow-drag-enter directive:

```
<div flow-drag-enter="style={border:'4px solid green'}" flow-drag-leave="style={}"
     ng-style="style">
</div>
```

**Comment by MartinNuc** [comment]
That's a great point! There is currently nothing for this behaviour and it would be great addition!

I think it should be quite easy to implement. [Here](https://github.com/flowjs/ng-flow/blob/master/src/directives/drag-events.js) is the source of drag-events directives in ng-flow Actually it could be a directive which has nothing to do with `ngx-flow`.

**Comment by MaximRobota** [comment]
Thanks for the quick response. I think this will be a very good addition, since many use your plugin! Thank you for your work!
