### ISSUE TITLE
Reject event 'fileAdded'

### ISSUE THREAD

**Issue by begust** [flowjs/ngx-flow#38]
In flow.js I can 'return false' to reject a file.  that does not seem to work here.

How do I reject a file from the fileAdded event?

**Comment by MartinNuc** [comment]
Interesting I didn't know about that feature!

This is indeed not possible in ngx-flow :-(

So far I came up with this kinda hacky solution which works:

```typescript
    this.flow.events$.subscribe(event => {
      switch (event.type) {
        case 'fileAdded':
          if (isFileAdded(event.event, event.type)) { // to tell Typescript that this event is fileAdded.
            const flowFile = event.event[0]; // grab flowFile which is being added
            const idToBeCanceled = flowFile.uniqueIdentifier; // and get it's unique id
            this.flow.transfers$
              .pipe(
                filter(uploadStatus => uploadStatus.transfers.some(transfer => transfer.id === idToBeCanceled)), // the file appears in transfers little bit later so we wait for it here
                map(uploadStatus => uploadStatus.transfers.find(transfer => transfer.id === idToBeCanceled)), // once it's there grab it
                take(1) // we will cancel it only once
              )
              .subscribe(transferToBeCanceled => this.flow.cancelFile(transferToBeCanceled)); // here we use ngx-flow to cancel this file upload
            return;
          }
    });

function isFileAdded(event: flowjs.FlowEvent, eventType: string): event is flowjs.FileAddedCallbackArguments {
  return eventType === 'fileAdded';
}
```

**Comment by begust** [comment]
Thank you for your response.   i will give you solution a try.
if fileadded can not return a value, can filesAdded be used by canceling each file?
I will test.

**Comment by begust** [comment]
I thank you greatly for your input.  I have decided to implement the following code:
            switch (event.type) {
                case 'fileAdded':
                    var file: flowjs.FlowFile = event.event[0] as flowjs.FlowFile;
                    if (file.file.size === 0) {
                        file.error = true;
                    }
                    return;
                case 'filesSubmitted':
                    var files: flowjs.FlowFile[] = event.event[0] as flowjs.FlowFile[];
                    files.forEach(file => {
                        if (file.error) { this.flow.flowJs.removeFile(file); }
                    })
                    if (this.flow.flowJs.files.length) {
                        this.flow.upload();
                    }
                    return;
            }
