### ISSUE TITLE
Remove private:true from package.json in order to be able to publish the package publicly

### ISSUE THREAD

**Issue by evilaliv3** [flowjs/ngx-flow#4]
```user@development:~/Development/ngx-flow$ npm publish
npm ERR! This package has been marked as private
npm ERR! Remove the 'private' field from the package.json to publish it.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2018-09-15T08_15_08_454Z-debug.log
```

https://github.com/flowjs/ngx-flow/blob/b54e53dffc1f2be7f92b120d9ebed44834d8d6b9/package.json#L14

**Comment by evilaliv3** [comment]
@MartinNuc: in the meantime i've published the package anyhow by removing the line locally before publishing the package.

**Comment by AidasK** [comment]
Yes, it was confusing for me too. I have never seen a project structured like that. Though maybe this is a thing for ngx projects? Is it recommended in ngx guide to structure the project like that?

**Comment by MartinNuc** [comment]
This is actually [recommended structure](https://github.com/angular/angular-cli/wiki/stories-create-library) for Angular libraries by angular-cli. Although I find it also little bit confusion when one sees it the first time, I would prefer to stick to the angular-cli structure for these reasons:

1. compatibility with future updates of angular-cli
2. it's de facto standard for Angular libs right now (might change in future, who knows)
3. we would have to eject webpack config and reconfigure

**Comment by AidasK** [comment]
Good for me, I prefer to use recommended structure by Angular
