### ISSUE TITLE
[BUG] Attaching [flow] and [flowAttributes] rendering multiple dialogs

### ISSUE THREAD

**Issue by Coly010** [flowjs/ngx-flow#44]
The following causes the file picker dialog to render multiple times:

```html
 <button
        flowButton
        [flow]="flow.flowJs"
        [flowAttributes]="{accept: 'application/zip'}"
    >
        Upload File
    </button>
```

My guess is that it's because `setup` is being called for every input set, attaching multiple listeners to the host component of the directive.

![image](https://user-images.githubusercontent.com/12140467/102370695-438ee200-3fb5-11eb-808e-6ecca5ddaeb5.png)

**Comment by vortaxg** [comment]
I had the same issue,
try to update input params order.

 <button
        flowButton
        **[flowAttributes]="{accept: 'application/zip'}"
        [flow]="flow.flowJs"**
    >
        Upload File
    </button>

**Comment by Coly010** [comment]
As crazy as that solution is, it worked. 

Whilst it _does_ work, I 100% think this should still be an issue to be resolved. input order _shouldn't_ matter.

@vortaxg Thanks for the help!!

**Comment by MartinNuc** [comment]
Definitely a bug! Thanks for pointing that out.

Can you please help me reproducing it? Both Chrome and Safari is showing the dialog only once. Where does it happen?

**Comment by Quentigus** [comment]
I've faced the same problem today (3 popup for 1 button click).
Adding `type="file"` to the `button` have fixed the problem on my application.

Versions :
- @flowjs/flow.js : ^2.14.1
- @flowjs/ngx-flow : ^0.4.6
