### ISSUE TITLE
dependencies.

### ISSUE THREAD

**Issue by begust** [flowjs/ngx-flow#48]
ngx-flow dependencies are limited to angular 8.

Can these be updated to a newer version of angular.

Currently I am building with angular 10.0

Brad

**Comment by MartinNuc** [comment]
It's [peer dependency](https://github.com/flowjs/ngx-flow/blob/master/projects/ngx-flow/package.json). Is it an issue?

You can make PR to bump it to newer version if you want.

**Comment by MartinNuc** [comment]
Released 0.4.6

Please let me know if it works fine now 🙏

**Comment by begust** [comment]
Thank you. This works for me.
