### ISSUE TITLE
Three times complete events fired.

### ISSUE THREAD

**Issue by hioymaci** [flowjs/ngx-flow#53]
If I canceled file upload with this: `this.flow.cancel();`, event:{type:'complete'} fires 3 times. Look the below picture.

![three_completed](https://user-images.githubusercontent.com/15131951/116818128-6390fd80-ab72-11eb-8dce-c543f793ea98.png)

I send an API request to server after file completed to check in server. But due to 3 times fires, it sends 3 requests. How can I fixed this problem? Is it bug? (I now I can add a counter but it will be ugly code).

**Comment by Mahesh-Kumar-N** [comment]
file submitted event too triggers multiple times, any update on this issue
