### ISSUE TITLE
Support for Angular 12

### ISSUE THREAD

**Issue by erkinyldz** [flowjs/ngx-flow#60]
Latest version does not support Angular 12 which results in dependency conflicts for ngx-flow when updating to Angular 12.

**Comment by LoganWlv** [comment]
I guess this is about to be fixed with https://github.com/flowjs/ngx-flow/commit/6913836fb5f2e94b45903479b3e12914fb2bb7a4

Though it breaks on travis, maybe we should use the latest stable of yarn (v1.22.11) instead of v1.3.2 @MartinNuc ?

**Comment by swieczorek-fis-sst** [comment]
same here

**Comment by dango85** [comment]
any plans of pushing out angular v12 compatible version?

**Comment by edWhoShouldBeWorking** [comment]
What's the best way to help with this?

**Comment by RoyceTheBiker** [comment]
One more developer here that would like to see support under ng12

**Comment by AidasK** [comment]
https://github.com/flowjs/ngx-flow/pull/86 related

**Comment by itsaplev** [comment]
ngx-flow v0.5.0 with angular 12 support is available

**Comment by RoyceTheBiker** [comment]
Thank you for your work to get support for Ng12.

How long before the module is updated on npmjs.com?
