### ISSUE TITLE
Error in server side compilation

### ISSUE THREAD

**Issue by Pasquale85** [flowjs/ngx-flow#7]
ReferenceError: window is not define in flow.js.

**Comment by MartinNuc** [comment]
@Pasquale85 Can you please try version 0.3.4? Also you will have to bump flowjs version:

```
"@flowjs/flow.js": "2.13.1",
```

**Comment by MartinNuc** [comment]
Oh and one more change: https://github.com/flowjs/ngx-flow#running-with-server-side-rendering-angular-universal

**Comment by MartinNuc** [comment]
Great to hear. Closing.

**Comment by Pasquale85** [comment]
Thanks so much!!
