### ISSUE TITLE
can not find @flowjs/flow.js declaration

### ISSUE THREAD

**Issue by touchsky2018** [flowjs/ngx-flow#81]
anyone know how to resolve this.

import Flow from '@flowjs/flow.js';

S7016: Could not find a declaration file for module '@flowjs/flow.js'. 'xxxxxxxx/node_modules/@flowjs/flow.js/src/flow.js' implicitly has an 'any' type.
  Try `npm i --save-dev @types/flowjs__flow.js` if it exists or add a new declaration (.d.ts) file containing `declare module '@flowjs/flow.js';`

21 import Flow from '@flowjs/flow.js';

无法找到模块“@flowjs/flow.js”的声明文件。“C:/FescoDev/09.source/frontend-electron/GsyfSys/node_modules/@flowjs/flow.js/src/flow.js”隐式拥有 "any" 类型。
  尝试使用 `npm i --save-dev @types/flowjs__flow.js` (如果存在)，或者添加一个包含 `declare module '@flowjs/flow.js';` 的新声明(.d.ts)文件ts(7016)

**Comment by akeresztesgh** [comment]
I installed the suggested type file: "npm i --save-dev @types/flowjs__flow.js"
Then, in my app module, I changed the flow import to:
import * as Flow from '@flowjs/flow.js';

then it worked.
